#ifndef HDFPP_PROPERTIES_SHARED_CREATE_MISSING_INTERMEDIATE_GROUPS_TEMPLATE_HPP
#define HDFPP_PROPERTIES_SHARED_CREATE_MISSING_INTERMEDIATE_GROUPS_TEMPLATE_HPP

#include "implementation/properties/shared/create_missing_intermediate_groups.hpp"

#endif
